---
name: Go
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '42 3 * * 4'

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go tip
        run: |
          sudo rm -fr /opt/hostedtoolcache/go /usr/local/go /usr/bin/go /bin/go
          curl -o go.tar.gz -L \
            https://github.com/AlekSi/golang-tip/releases/download/tip/master.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go.tar.gz
          sudo ln -s /usr/local/go/bin/* /usr/local/bin/
          go version
          rm go.tar.gz

      - name: Run tests
        run: go test -v
